const list = [
  { id: 1, dish_name: "Dal Fry", price: 90, rating: 9, amount: 1 },
  { id: 2, dish_name: "Chana Masala", price: 120, rating: 9.2, amount: 1 },
  { id: 3, dish_name: "Mix veg", price: 100, rating: 9.5, amount: 1 },
  { id: 4, dish_name: "Veg Handi", price: 300, rating: 8, amount: 1 },
  { id: 5, dish_name: "Paneer Palak", price: 150, rating: 8.1, amount: 1 },
  { id: 6, dish_name: "Butter Paneer", price: 160, rating: 7, amount: 1 },
  { id: 7, dish_name: "Fry Papad", price: 50, rating: 8.5, amount: 1 },
  { id: 8, dish_name: "Veg Soup", price: 100, rating: 9, amount: 1 },
  { id: 9, dish_name: "Chapati", price: 12, rating: 6, amount: 1 },
  { id: 10, dish_name: "Bhakri", price: 18, rating: 7.6, amount: 1 },
  { id: 11, dish_name: "Plain Paratha", price: 20, rating: 9.2, amount: 1 },
  { id: 12, dish_name: "Butter Paratha", price: 25, rating: 8.9, amount: 1 },
  { id: 13, dish_name: "Pav Bhaji", price: 150, rating: 9, amount: 1 },
  { id: 15, dish_name: "Butter PavBhaji", price: 200, rating: 9, amount: 1 },
  { id: 14, dish_name: "Green Salad", price: 50, rating: 8, amount: 1 },
  { id: 17, dish_name: "Veg Kheema", price: 230, rating: 9, amount: 1 },
  {
    id: 18,
    dish_name: "Paneer Mushroom Masala",
    price: 350,
    rating: 8,
    amount: 1,
  },
  { id: 19, dish_name: "Sada Rice", price: 150, rating: 9.1, amount: 1 },
  { id: 20, dish_name: "Jeera Rice", price: 200, rating: 8.6, amount: 1 },
  { id: 21, dish_name: "Veg Pulav", price: 220, rating: 7.2, amount: 1 },
];
export default list;
